FROM mirrors.tencent.com/drug_ai/g-tlinux2.2-python3.6-cuda10.1-cudnn7.6-pytorch1.4-torchvision0.5-openmpi4.0.3-nccl2.5.6-ofed4.6-horovod-rdkit202003.3.0:latest
# RUN pip3 install --upgrade pip && \
# pip3 install jieba && \
# HOROVOD_GPU_OPERATIONS=NCCL pip3 install horovod
# RUN pip3 install networkx
# RUN conda install -c rdkit rdkit
# SHELL ["source", "~/.bashrc"]
ENV PATH /root/anaconda3/bin:$PATH
# RUN echo "export PATH="/root/anaconda3/bin:$PATH"" >> ~/.bashrc && \
RUN conda init bash && \
# conda activate base && \
pip3 install dgl
# conda install -c dglteam dgl
# /bin/bash -c "source ~/.bashrc" && \
# # /bin/bash -c "conda init bash" && \
# /bin/bash -c "conda activate base" && \
# /bin/bash -c "conda install -c dglteam dgl"
# RUN pip3 install dgl
# RUN pip3 install splitter
# RUN
# RUN
# RUN pip3 install dgl
# RUN conda install -c dglteam dgl
# RUN /bin/bash -c "conda install -c dglteam dgl"
# RUN pip3 install -i http://mirror-sng.oa.com/pypi/web/simple/ --trusted-host mirror-sng.oa.com torch_geometric --no-cache